name: CICD workflow for Manga Characters static web app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name: Set up SonarCloud Scanner
        uses: SonarSource/sonarqube-scan-action@v4.2.1
        with:
          sonar.projectKey: omkar-shelke25_Manga-Characters-static-web-deploy-by-docker-file  # Replace with your actual project key
          sonar.organization: omkar-shelke25  # Replace with your actual organization key
          sonar.host.url: https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Make sure the token is set in your secrets
