name: CICD workflow for Manga Characters static web app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          push: true
          tags: omkara25/manga-web-image:latest
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKERLOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERPASSWORD }}
