name: CICD workflow for Manga Characters static web app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Use environment variables
        run: |
          echo "PASSWORD is ${{ secrets.PASSWORD }}"
          echo "SONAR token is ${{ secrets.SONAR }}"
          echo "USERNAME is ${{ secrets.USERNAME }}"
