name: CICD workflow for Manga Characters static web app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Docker Setup Docker
        uses: docker/setup-docker-action@v4
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERLOGIN }} -p ${{ secrets.DOCKERPASSWORD }}
