name: CICD workflow for Manga Characters static web app

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: make dirctory
        run:  mkdir -p Project-Data
      - name: show list of directory
        run: ls
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.10.0
      - name: docker login
        run: docker login -u omkara25 -p 182503@#Om
      - name: build image
        run: docker build -t manga-web-image .
      - name: push images
        run: docker image push manga-web-image
          
        
        

    

      
