name: CICD workflow for Manga Characters static web app

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.10.0
      - name: docker login
        run: docker login -u {} -p {}
      - name: build image
        run: docker build -t manga-web-image .
      - name: push images
        run: |
          docker tag manga-web-image omkara25/manga-web-image:latest
          docker image push omkara25/manga-web-image:latest
          
        
        

    

      
